### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by si458** [adminerevo/adminerevo#22]
will you be releasing docker images for you forked repo?

**Comment by RoyBellingan** [comment]
Dude is 1 file...

**Comment by Letme** [comment]
I find it very convenient as you simply put it in your Kubernetes deployment, and have it available per demand with all dependencies installed also for non PHP projects (I use it for various projects which have databases just because I love the interface and look and feel).
So I would also appreciate the docker image with the same port exposure as the old adminer.

**Comment by LionelLaffineur** [comment]
FYI: https://github.com/TimWolla/docker-adminer/discussions/161

**Comment by timwsuqld** [comment]
I've done a quick hack job of getting this working based on https://github.com/TimWolla/docker-adminer. I needed it building in our CI on Gitlab, and I also wanted to use the Debian Apache PHP image instead of the built in PHP Dev server.
Hopefully this will help anyone else who needs this running. https://github.com/suaustralia/adminerevo-docker

**Comment by ssheduardo** [comment]
I have successfully created a Docker image with AdminerEvo by leveraging the project available at [this GitHub repository](https://github.com/TimWolla/docker-adminer).

The Docker Compose configuration file (docker-compose.yml) I utilized for this purpose is structured as follows:

```
version: '3'
services:
  adminerevo:
      image: ${VERSION} 
      restart: always
      container_name: adminerevo  
      environment:
          ADMINER_PLUGINS: "tables-filter dump-date"
      labels:
        - "traefik.enable=true"        
        - "traefik.http.routers.adminerevo-secure.entrypoints=web"
        - "traefik.http.routers.adminerevo-secure.rule=Host(`adminerevo.local`)"
#Docker Networks
networks:
    default:
        external: true
        name: ${NETWORK}
```
Additionally, I have utilized an environment variable configuration file (.env) with the following content:

```
NETWORK="traefik_net"
VERSION="ssheduard/adminerevo:4.8.3-php8.2"
```

It's worth noting that this setup utilizes AdminerEvo version 4.8.3 with PHP 8.2.
 If Traefik is not desired, the Docker Compose configuration can be simplified as follows:
```
version: '3'
services:
  adminerevo:
      image: ${VERSION} 
      restart: always
      container_name: adminerevo  
      environment:
          ADMINER_PLUGINS: "tables-filter dump-date"
```
